name       : anthy
version    : 9100h
release    : 1
source     :
    - http://gigenet.dl.osdn.jp/anthy/37536/anthy-9100h.tar.gz : d256f075f018b4a3cb0d165ed6151fda4ba7db1621727e0eb54569b6e2275547
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.core
summary    : Anthy is a library for Japanese text input.
description: |
    Anthy is a library for Japanese text input.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
